package dark_forest;

public class Game extends javax.swing.JFrame {

    public Menu menu = new Menu();
    public Player player = new Player("test");
    public Enemy target;
    
    public Game() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Start = new javax.swing.JPanel();
        BPlay = new javax.swing.JButton();
        BLoad = new javax.swing.JButton();
        BExit = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Combat = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        Actions = new javax.swing.JPanel();
        Attack_c = new javax.swing.JButton();
        Spell_c = new javax.swing.JButton();
        Defend = new javax.swing.JButton();
        Heal = new javax.swing.JButton();
        Check = new javax.swing.JButton();
        Esc = new javax.swing.JButton();
        Attack = new javax.swing.JPanel();
        Normal_A = new javax.swing.JButton();
        Swift_A = new javax.swing.JButton();
        Heavy_A = new javax.swing.JButton();
        Cancel_A = new javax.swing.JButton();
        Spell = new javax.swing.JPanel();
        Fire_S = new javax.swing.JButton();
        Ice_S = new javax.swing.JButton();
        Light_S = new javax.swing.JButton();
        Cancel_S = new javax.swing.JButton();
        jProgressBar1 = new javax.swing.JProgressBar();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setPreferredSize(new java.awt.Dimension(640, 480));
        setResizable(false);
        setSize(new java.awt.Dimension(640, 480));
        getContentPane().setLayout(null);

        Start.setLayout(null);

        BPlay.setBackground(new java.awt.Color(60, 63, 63));
        BPlay.setForeground(new java.awt.Color(204, 204, 204));
        BPlay.setText("PLAY");
        BPlay.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BPlay.setOpaque(false);
        BPlay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BPlayActionPerformed(evt);
            }
        });
        Start.add(BPlay);
        BPlay.setBounds(195, 170, 250, 50);

        BLoad.setBackground(new java.awt.Color(60, 63, 63));
        BLoad.setForeground(new java.awt.Color(204, 204, 204));
        BLoad.setText("LOAD");
        BLoad.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BLoad.setOpaque(false);
        Start.add(BLoad);
        BLoad.setBounds(195, 240, 250, 50);

        BExit.setBackground(new java.awt.Color(60, 63, 63));
        BExit.setForeground(new java.awt.Color(204, 204, 204));
        BExit.setText("EXIT");
        BExit.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BExit.setOpaque(false);
        BExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BExitMouseClicked(evt);
            }
        });
        Start.add(BExit);
        BExit.setBounds(195, 310, 250, 50);

        jLabel1.setFont(new java.awt.Font("Panton Black Caps", 0, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("DARK FOREST");
        Start.add(jLabel1);
        jLabel1.setBounds(145, 67, 360, 59);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dark_forest/RI.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        Start.add(jLabel2);
        jLabel2.setBounds(0, 0, 640, 480);

        getContentPane().add(Start);
        Start.setBounds(0, 0, 640, 480);

        Combat.setLayout(null);
        Combat.setVisible(true);

        jPanel1.setBackground(new java.awt.Color(0, 51, 153));
        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setLayout(null);

        Actions.setOpaque(false);

        Attack_c.setText("Attack");
        Attack_c.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Attack_c.setOpaque(false);
        Attack_c.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Attack_cActionPerformed(evt);
            }
        });

        Spell_c.setText("Spell");
        Spell_c.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Spell_c.setOpaque(false);
        Spell_c.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Spell_cActionPerformed(evt);
            }
        });

        Defend.setText("Defend");
        Defend.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Defend.setOpaque(false);

        Heal.setText("Heal");
        Heal.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Heal.setOpaque(false);

        Check.setText("Check");
        Check.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Check.setOpaque(false);

        Esc.setText("Escape !");
        Esc.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Esc.setOpaque(false);

        javax.swing.GroupLayout ActionsLayout = new javax.swing.GroupLayout(Actions);
        Actions.setLayout(ActionsLayout);
        ActionsLayout.setHorizontalGroup(
            ActionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 226, Short.MAX_VALUE)
            .addGroup(ActionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(ActionsLayout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(ActionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(Attack_c, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Defend, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Check, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(ActionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(Spell_c, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Heal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Esc, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(22, Short.MAX_VALUE)))
        );
        ActionsLayout.setVerticalGroup(
            ActionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 174, Short.MAX_VALUE)
            .addGroup(ActionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(ActionsLayout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(ActionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Attack_c, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Spell_c, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(ActionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Defend, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Heal, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(ActionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Check, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Esc, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        jPanel1.add(Actions);
        Actions.setBounds(9, 3, 226, 174);

        Attack.setOpaque(false);
        Attack.setVisible(false);

        Normal_A.setText("Normal Attack");
        Normal_A.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Normal_A.setOpaque(false);

        Swift_A.setText("Swift Strike");
        Swift_A.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Swift_A.setOpaque(false);

        Heavy_A.setText("Heavy Strike");
        Heavy_A.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Heavy_A.setOpaque(false);

        Cancel_A.setText("Cancel");
        Cancel_A.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Cancel_A.setOpaque(false);
        Cancel_A.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cancel_AActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout AttackLayout = new javax.swing.GroupLayout(Attack);
        Attack.setLayout(AttackLayout);
        AttackLayout.setHorizontalGroup(
            AttackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AttackLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(AttackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AttackLayout.createSequentialGroup()
                        .addComponent(Normal_A, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Swift_A, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(AttackLayout.createSequentialGroup()
                        .addComponent(Heavy_A, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Cancel_A, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        AttackLayout.setVerticalGroup(
            AttackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AttackLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(AttackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Normal_A, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Swift_A, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(AttackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Heavy_A, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Cancel_A, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(66, Short.MAX_VALUE))
        );

        jPanel1.add(Attack);
        Attack.setBounds(9, 3, 226, 174);

        Spell.setOpaque(false);
        Spell.setVisible(false);

        Fire_S.setText("Fire Blast [50]");
        Fire_S.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Fire_S.setOpaque(false);

        Ice_S.setText("Ice Spear [30]");
        Ice_S.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Ice_S.setOpaque(false);

        Light_S.setText("<html>\n]Lightning Bolt </br>\n[80]\n</html>");
        Light_S.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Light_S.setOpaque(false);

        Cancel_S.setText("Cancel");
        Cancel_S.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Cancel_S.setOpaque(false);
        Cancel_S.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cancel_SActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout SpellLayout = new javax.swing.GroupLayout(Spell);
        Spell.setLayout(SpellLayout);
        SpellLayout.setHorizontalGroup(
            SpellLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SpellLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(SpellLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SpellLayout.createSequentialGroup()
                        .addComponent(Fire_S, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Ice_S, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(SpellLayout.createSequentialGroup()
                        .addComponent(Light_S, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Cancel_S, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        SpellLayout.setVerticalGroup(
            SpellLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SpellLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(SpellLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Fire_S, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Ice_S, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(SpellLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Cancel_S, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Light_S, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(66, Short.MAX_VALUE))
        );

        jPanel1.add(Spell);
        Spell.setBounds(9, 3, 226, 174);

        jProgressBar1.setBackground(new java.awt.Color(51, 51, 51));
        jProgressBar1.setForeground(new java.awt.Color(0, 102, 51));
        jProgressBar1.setValue((player.getHP()*100/player.getmax_HP()));
        jPanel1.add(jProgressBar1);
        jProgressBar1.setBounds(240, 20, 310, 12);

        Combat.add(jPanel1);
        jPanel1.setBounds(0, 290, 640, 190);

        jPanel2.setBackground(new java.awt.Color(0, 51, 153));
        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Combat.add(jPanel2);
        jPanel2.setBounds(0, 0, 640, 50);

        getContentPane().add(Combat);
        Combat.setBounds(0, 0, 640, 480);

        setSize(new java.awt.Dimension(656, 518));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BExitMouseClicked
       this.dispose();
    }//GEN-LAST:event_BExitMouseClicked

    private void BPlayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BPlayActionPerformed
       Combat.setVisible(true);
       target = new Enemy(player.getLvl());
       Start.setVisible(false);
       
       if(player.getHP()*100/player.getmax_HP() > 75)
        {jProgressBar1.setForeground(new java.awt.Color(51, 153, 0));}
       else if(player.getHP()*100/player.getmax_HP() > 35)
        {jProgressBar1.setForeground(new java.awt.Color(204, 204, 0));}
       else
        {jProgressBar1.setForeground(new java.awt.Color(153, 0, 0));}
    }//GEN-LAST:event_BPlayActionPerformed

    private void Attack_cActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Attack_cActionPerformed
        Attack.setVisible(true);
        Actions.setVisible(false);
    }//GEN-LAST:event_Attack_cActionPerformed

    private void Spell_cActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Spell_cActionPerformed
        Spell.setVisible(true);
        Actions.setVisible(false);
    }//GEN-LAST:event_Spell_cActionPerformed

    private void Cancel_AActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cancel_AActionPerformed
        Attack.setVisible(false);
        Actions.setVisible(true);
    }//GEN-LAST:event_Cancel_AActionPerformed

    private void Cancel_SActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cancel_SActionPerformed
        Spell.setVisible(false);
        Actions.setVisible(true);
    }//GEN-LAST:event_Cancel_SActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Actions;
    private javax.swing.JPanel Attack;
    private javax.swing.JButton Attack_c;
    private javax.swing.JButton BExit;
    private javax.swing.JButton BLoad;
    private javax.swing.JButton BPlay;
    private javax.swing.JButton Cancel_A;
    private javax.swing.JButton Cancel_S;
    private javax.swing.JButton Check;
    private javax.swing.JPanel Combat;
    private javax.swing.JButton Defend;
    private javax.swing.JButton Esc;
    private javax.swing.JButton Fire_S;
    private javax.swing.JButton Heal;
    private javax.swing.JButton Heavy_A;
    private javax.swing.JButton Ice_S;
    private javax.swing.JButton Light_S;
    private javax.swing.JButton Normal_A;
    private javax.swing.JPanel Spell;
    private javax.swing.JButton Spell_c;
    private javax.swing.JPanel Start;
    private javax.swing.JButton Swift_A;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JProgressBar jProgressBar1;
    // End of variables declaration//GEN-END:variables
}
